### ISSUE TITLE
Password field doesn't work in IE8

### ISSUE THREAD

**Issue by entozoon** [vote539/placeholdr#8]
Admittedly, and frustratingly, you don't specifically support IE8, but worth mentioning that input type text works fine.
type password doesn't though, specifically because you can't change input types, i.e:
```
$this.attr("type", "text");
```

**Comment by vote539** [comment]
That's right, the password placeholder appears as dots in IE8 since IE8 doesn't let you change the input field type on the fly.  I mention this in the README.  It's a concession I had to make to keep file size below 1K.  However, all the other functionality works fine in IE8 (clearing the field on form submit or on password field focus, etc).

If you like, you're free to fork this repo and make a version of Placeholdr that more fully supports password placeholders in IE 8.  I can link to it from the readme. :smiley:
